### ISSUE TITLE
Dragon Core texture rework

### ISSUE THREAD

**Issue by Tomanex** [DragonMountsTeam/Dragon-Mounts-2-Continued#24]
Decided to fix the texture of the Dragon Core.
Now has a mini end crystal inside that spins indefinitely.
[Dragon Core.zip](https://github.com/user-attachments/files/17685521/Dragon.Core.zip)

**Comment by Tomanex** [comment]
HD
![shulker-2](https://github.com/user-attachments/assets/ae36a74e-83ff-4533-b323-da7d86b22c79)

**Comment by 2190303755** [comment]
model required

**Comment by Tomanex** [comment]
> preview is no use, model required. bedrock model is also allowed because I can manually translate it to java

[Dragon Core.zip](https://github.com/user-attachments/files/17771125/Dragon.Core.zip)

Did I not send the files already or you mean the model itself?

**Comment by 2190303755** [comment]
I don't know where does the lower right corner of the texture correspond to your modified model

**Comment by Tomanex** [comment]
> I don't know where does the lower right corner of the texture correspond to your modified model

Ah I see the confusion, alright I'll replace it without the lower textures. Here. 

[dragon_shulker.zip](https://github.com/user-attachments/files/17771184/dragon_shulker.zip)
